### ISSUE TITLE
Multi-line URLs for poster and Discover endpoint adds spaces

### ISSUE THREAD

**Issue by johnruth** [fewieden/MMM-MovieInfo#3]
When I tried to use the module I got an HTTP status code of 401.  It didn't like my API key because of an extra space.  I believe that the "\" character used to wrap multi-line strings is adding a space.  So, in node_helper.js an extra space is included after primary_release_date.gte and api_key.  In MMM-MovieInfo.js a space is added before v2$ in poster.src.

After removing these, I was able to use the module without errors.

**Comment by fewieden** [comment]
Hi John, thanks for reporting. I merged a pull request #1  which among others adressed this problem, so it should be fixed now.

**Comment by johnruth** [comment]
Oh, great!
