### ISSUE TITLE
 Api key

### ISSUE THREAD

**Issue by Donlar714** [fewieden/MMM-MovieInfo#5]
how and where do i input the api key. sorry, im a total noob. i have everything else done but i dont see any movies when i start the mirror.

**Comment by fewieden** [comment]
Your entry in the config.js file should look like this:

```
{
    module: 'MMM-MovieInfo',
    position: 'top_right',
    config: {
        api_key: 'YOUR_API_KEY'
    }
}
```

**Comment by fewieden** [comment]
Closed due to inactivity.
