### ISSUE TITLE
Doesn't Work

### ISSUE THREAD

**Issue by Mert4531** [fewieden/MMM-MovieInfo#6]
I setup this module, but it doesn't seems anything. I create an API key and I add config.js and MovieInfo.js folder. However an error occurred because of api_key variable is boolean so it can be  just true or false. Please help me for fix this issue

**Comment by fewieden** [comment]
@Mert4531 sorry for the late reply.

You shouldn't modify anything else than the config.js file.

The minimum config to get this module working is:

```js
{
  module: 'MMM-MovieInfo',
  position: 'top_right',
  config: {
    api_key: 'YOUR_API_KEY'
  }
}
```

Just tested it successfully with the newest version.
