### ISSUE TITLE
Discovery?

### ISSUE THREAD

**Issue by ghost** [fewieden/MMM-MovieInfo#7]
hey could you leave an example of a workign config + discovery setup? i have 2 ogf these in the same window but i want them to show different genres or popularity vs upcoming etc

**Comment by fewieden** [comment]
@JoshuaShelswell 

the following config would show you the most popular drama movies that have at least votes from 10 people.

```js
{
  module: 'MMM-MovieInfo',
  position: 'top_right',
  config: {
    api_key: 'YOUR_API_KEY',
    discover: {
      with_genres: 18,
      sort_by: 'vote_average.desc',
      'vote_count.gte': 10
    }
  }
}
```

Or upcoming movies:

```js
{
  module: 'MMM-MovieInfo',
  position: 'top_right',
  config: {
    api_key: 'YOUR_API_KEY',
    discover: {
      'primary_release_date.gte': 'now',
      'primary_release_date.lte': 'month'
    }
  }
}
```

For more examples check out the readme https://github.com/fewieden/MMM-MovieInfo#discover-configuration-examples

**Comment by ghost** [comment]
Awesome, thanks so much
