### ISSUE TITLE
MMM-MovieInfo install instructions

### ISSUE THREAD

**Issue by DennisEJ** [fewieden/MMM-MovieInfo#8]
I'm a newbie to MM but have installed several modules.  I tried to install MMM-MovieInfo but when I looked I see the line that say "install this Repo to your module directory"  but I don't understand the phrase Rep.  Normally I see a line that say " copy and paste git some other information git" But I don't see the line that I'm supposed to copy and paste to the module directory. Can you give me more information on what I'm missing.
Thanks
Dennis N6NG

**Comment by fewieden** [comment]
@DennisEJ a GitHub repo can be cloned in different ways. If you don't have a preferred method I suggest using the https method behind the green button on the repository.

![image](https://user-images.githubusercontent.com/9334168/166269341-042d2751-8524-4df5-93f7-0f9177129707.png)

If you installed MagicMirror in your home directory you can run those commands.

```bash
cd ~/MagicMirror/modules
git clone https://github.com/fewieden/MMM-MovieInfo.git
cd MMM-MovieInfo
npm i --production
```

**Comment by DennisEJ** [comment]
Thank you
Dennis
